=== sabrie/TelerikAcademy/Programming/06.Databases/16.XMLBasics/Students/students.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           attributeFormDefault="unqualified" elementFormDefault="qualified" 
           targetNamespace="urn:students" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="sex" type="xs:string" />
              <xs:element name="birthdate" type="xs:string" />
              <xs:element name="phone" type="xs:string" />
              <xs:element name="email" type="xs:string" />
              <xs:element name="course" type="xs:string" />
              <xs:element name="specialty" type="xs:string" />
              <xs:element name="faculty-number" type="xs:unsignedInt" />
              <xs:element name="passed-exams">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="exam">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="exam-name" type="xs:string" />
                          <xs:element name="tutor" type="xs:string" />
                          <xs:element name="score" type="xs:decimal" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="culture" type="xs:string" use="required" />
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sabrie/TelerikAcademy/Programming/06.Databases/16.XMLBasics/StudentsConsole/students.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="students.xslt"?>
<students culture="en-US" 
          xmlns="urn:studentss"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.nakov.com/schemas/students file://././students.xsd"
          name="students" >
  <student>
    <name>Pesho Peshev</name>
    <sex>Male</sex>
    <birthdate>10.10.1991</birthdate>
    <phone>0888 123 456</phone>
    <email>pesho@gmail.com</email>
    <course>Programming</course>
    <specialty>Programming</specialty>
    <faculty-number>123456</faculty-number>
    <passed-exams>
      <exam>
        <exam-name>C# Part 1</exam-name>
        <tutor>Svetlin Nakov</tutor>
        <score>6.0</score>
      </exam>
      <exam>
        <exam-name>JavaScript Part 1</exam-name>
        <tutor>Doncho Minkov</tutor>
        <score>5.0</score>
      </exam>
    </passed-exams>
  </student>
</students>
